### ISSUE TITLE
Supply toybox with AppManager

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/AppManager#84]
AppManager use various commands which are not available on AP 23 or earlier and often some commands are not available either purposefully or due to vendor's mistake. I intend to use [toybox](https://github.com/landley/toybox) to fix this issue. The benefit of toybox over busybox is that it also comes built-in with Android and is actively developed for this platform (and that it's developed by the same author who started busybox development). It's license (0BSD) is also compatible with GPL-3.0 license.

@IzzySoft Does F-Droid support the use of git submodules? I intend to add the project as a submodule to this project.

**Comment by IzzySoft** [comment]
> Does F-Droid support the use of git submodules?

Yes, it does. Make sure the corresponding keyword is enabled in the metadata build block then (`*.yml`; manual MR required for the first version using it), e.g.:

```yaml
Builds:
  - versionName: '3.0'
    versionCode: 30
    commit: v3.0
    subdir: app
    submodules: true
    gradle:
      - yes
```

(see the line with `submodules: true` which enables that feature)

PS: a pity that toybox is that limited… Do you know which Android version introduced it as being built-in?
